# .goreleaser.yml
before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - id: "myapp"
    main: ./cmd/myapp/main.go
    binary: myapp
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w
archives:
  - id: "myapp"
    builds:
      - "myapp"
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
release:
  github:
    owner: drpaneas
    name: archimedes